"""Authoritative persistence layer package (DATA-001, ADR-012)."""

from app.persistence.database import (
    Base,
    get_db_session,
    get_engine,
    get_session_maker,
)
from app.persistence.models import (
    Attempt,
    Child,
    ChildMastery,
    Consent,
    CurriculumItem,
    CurriculumSkill,
    CurriculumVersion,
    Device,
    DomainEvent,
    Guardian,
    MasteryHistory,
    OutboxEvent,
    Session,
    Turn,
    VersionMetadata,
)
from app.persistence.repositories import (
    AttemptRepository,
    ConsentRepository,
    ConsentRevokedError,
    CurriculumRepository,
    DuplicateKeyError,
    EventOutboxRepository,
    ImmutabilityViolationError,
    NotFoundError,
    OptimisticLockError,
    PersistenceError,
    SessionRepository,
)
from app.persistence.unit_of_work import (
    InjectedFailureError,
    ResolvedTurnOutcome,
    ResolvedTurnUnitOfWork,
)

__all__ = [
    "Attempt",
    "AttemptRepository",
    "Base",
    "Child",
    "ChildMastery",
    "Consent",
    "ConsentRepository",
    "ConsentRevokedError",
    "CurriculumItem",
    "CurriculumRepository",
    "CurriculumSkill",
    "CurriculumVersion",
    "Device",
    "DomainEvent",
    "DuplicateKeyError",
    "EventOutboxRepository",
    "Guardian",
    "ImmutabilityViolationError",
    "InjectedFailureError",
    "MasteryHistory",
    "NotFoundError",
    "OptimisticLockError",
    "OutboxEvent",
    "PersistenceError",
    "ResolvedTurnOutcome",
    "ResolvedTurnUnitOfWork",
    "Session",
    "SessionRepository",
    "Turn",
    "VersionMetadata",
    "get_db_session",
    "get_engine",
    "get_session_maker",
]
