"""Observable protocol reason codes for transport validation and recovery (API-006, SEC-004)."""

from enum import Enum


class ProtocolReasonCode(str, Enum):
    """Reason codes returned for protocol sequencing, deduplication, and recovery checks."""

    ACCEPTED = "ACCEPTED"
    DUPLICATE_MESSAGE = "DUPLICATE_MESSAGE"
    OUT_OF_ORDER_SEQUENCE = "OUT_OF_ORDER_SEQUENCE"
    SEQUENCE_GAP = "SEQUENCE_GAP"
    STALE_STATE_VERSION = "STALE_STATE_VERSION"
    STALE_TURN = "STALE_TURN"
    SESSION_EXPIRED = "SESSION_EXPIRED"
    SESSION_NOT_FOUND = "SESSION_NOT_FOUND"
    SESSION_TERMINAL = "SESSION_TERMINAL"
    INVALID_PROTOCOL_VERSION = "INVALID_PROTOCOL_VERSION"
    INVALID_TIMESTAMP = "INVALID_TIMESTAMP"
    MAX_RESENDS_EXCEEDED = "MAX_RESENDS_EXCEEDED"
    ACK_MISMATCH = "ACK_MISMATCH"
    CORRUPT_ENVELOPE = "CORRUPT_ENVELOPE"
    UNEXPECTED_ENVELOPE_TYPE = "UNEXPECTED_ENVELOPE_TYPE"
